# Welcome to Jekyll!

title: Rumbaugh Group # your site title
author: wAOndering # You :P
description: > # Meta description of Homepage
  Rumbaugh Group - Neuroscience Lab at The Scripps Research Institute - Understand  the  links  between  Autism Spectrum Disorder (ASD) genetic  risk,  resulting  distributed brain connectivity impairments, and their impact on ASD-­relevant behaviors
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rumbaugh.scripps.ufl.edu/" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Rumbaugh
  links:
    - https://twitter.com/GavinRumbaugh
   # - https://www.facebook.com/ben.balter
   #  - https://www.linkedin.com/in/BenBalter
   # - https://plus.google.com/+BenBalter
   # - https://github.com/benbalter


# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'Team', link: '/the-team'}
  - {name: 'Research', link: '/research'}
  - {name: 'Tools', link: '/tools'}
  - {name: 'Publications', link: '/publications'}
  - {name: 'Gallery', link: '/lab-gallery'}
  - {name: 'News', link: '/news'}
  - {name: 'Contact', link: '/contact'}
  - {name: 'For Families', link: '/families'}

tagline: >
  Understand  the  links  between  Autism Spectrum Disorder (ASD) genetic  risk,  resulting  distributed brain connectivity impairments, and their impact on ASD-­relevant behaviors

hero_img: posts/research_lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: gavinrumbaugh@ufl.edu # email for form submission
twitter_username: GavinRumbaugh # replace with your_twitter_username or comment to remove link from footer
github_username:  RumbaughLab # replace with your_github_username or comment to remove link from footer
# instagram_username: GavinRumbaugh # replace with your_instagram_username or comment to remove link from footer
pubmed_search: rumbaugh+g
biorxiv_search: author1%3Arumbaugh%2Bg%20jcode%3Abiorxiv%20numresults%3A10%20sort%3Arelevance-rank%20format_result%3Astandard

disqus:
  shortname: GavinRumbaugh # to enable comments replace with your_disqus_shortname

google_tag_manager: GTM-5XRDCW2 # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

# service_worker: true

# BUILD SETTINGS
markdown: kramdown
# highlighter: rouge # or pygments or null
theme: minima #jekyll-sleek # Uncomment if you're using the theme as a ruby gem
# exclude:
#   - README.md
#   - node_modules
#   - script
#   - package.json
#   - package-lock.json
#   - Gemfile
#   - Gemfile.lock
#   - vendor
#   - npm-debug.log
#   - gulpfile.js
#   - sleek.jpg

# include: ['_pages']
# permalink: /:title/

# compress_html:
#   clippings: all

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
